" entry point for config. ~/.vimrc should just source this file or symlink to it
so ~/.dotfiles/vim/rcs/setup
so ~/.dotfiles/vim/rcs/settings
so ~/.dotfiles/vim/rcs/bindings
so ~/.dotfiles/vim/rcs/styles
so ~/.dotfiles/vim/rcs/custom
