brew cask install 1password
brew cask install caffeine
brew cask install disk-inventory-x
brew cask install dropbox
brew cask install flux
brew cask install limechat
brew cask install skype
brew cask install steam
brew cask install vlc
