# antigen setup/config
cd # TODO: figure out why this sometimes starts new sessions at /
source ~/.dotfiles/zsh/antigen.zsh
antigen use oh-my-zsh
antigen bundle z
# antigen bundle git
# antigen bundle git/git contrib/completion/git-completion.zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme lukebergen/dotfiles zsh/themes/lukebergen

antigen apply

# PATH setup
export PATH="$PATH:/usr/local/bin:/usr/local/sbin"        # local bins and such
export PATH="$PATH:$HOME/.rbenv/bin:$HOME/.rbenv/shims"   # rbenv
export PATH="$PATH:$HOME/.dotfiles/bin"                   # personal scripts and such
export PATH="$PATH:$HOME/.npm-packages/bin"                   # npm -g installed things

export GOPATH=$HOME/code/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# Ignore commands that start with a space (curling with passwords, etc...)
setopt HIST_IGNORE_SPACE

# init rbenv
eval "$(rbenv init - --no-rehash)"

# aliases
alias be="bundle exec"
alias fs="foreman start"
alias befs="bundle exec foreman start"
alias befr="bundle exec foreman run"
alias gs="git status -s"
alias gb="git branch"
alias gc="git checkout \$1"
alias gl="git log --pretty=format:\"%h%x09%an%x09%ad%x09%s\" --no-merges \$1"
alias gd="git diff"
alias ll="ls -al"
#alias serve="ruby -run -e httpd . -p \$1"
alias fix_video="sudo killall VDCAssistant"
alias R="R --silent"
alias vimx='vim -x --cmd "set cryptmethod=blowfish2" --cmd "set nobackup" --cmd "set noswapfile" --cmd "set viminfo=\"\"" -u NONE'
alias dotfiles="vim ~/.dotfiles"
alias dockclean='docker rm $(docker ps -a -q -f status=exited); docker rmi $(docker images -f "dangling=true" -q)'
alias rc='vim ~/.dotfiles/zsh/zshrc'

# miscelanious configuration stuff
export PGDATA="/usr/local/var/postgres"
export EDITOR=vim

export ARCHFLAGS="-arch x86_64"

unsetopt inc_append_history
unsetopt share_history

# This fixes the <enter> inserting ^M instead of actually sending enter to some programs issue that came up for god knows what reason
stty icrnl
stty sane

# added by travis gem
# [ -f /Users/lukebergen/.travis/travis.sh ] && source /Users/lukebergen/.travis/travis.sh
